"""initial

Revision ID: 328756284800
Revises: 
Create Date: 2026-03-02 12:57:08.595895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328756284800'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SR', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('f_low_woman', sa.Float(), nullable=False),
    sa.Column('f_high_woman', sa.Float(), nullable=False),
    sa.Column('f_low_man', sa.Float(), nullable=False),
    sa.Column('f_high_man', sa.Float(), nullable=False),
    sa.Column('target_db', sa.Float(), nullable=False),
    sa.Column('path_audio', sa.String(length=500), nullable=False),
    sa.Column('path_demographics', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('params')
    # ### end Alembic commands ###
