"""Add tsallis_q to params

Revision ID: 3644d79c6f61
Revises: 328756284800
Create Date: 2026-04-07 09:46:40.820198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3644d79c6f61'
down_revision = '328756284800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('params', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tsallis_q', sa.Float(), nullable=False, server_default='1.3'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('params', schema=None) as batch_op:
        batch_op.drop_column('tsallis_q')

    # ### end Alembic commands ###
